version: "3"

services:

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    expose:
      - 9200
    ports:
      - "9200:9200"
    env_file:
      - .env

  redis:
    image: redis
    expose:
      - 6379
    ports:
      - "6379:6379"
    command:
      - redis-server
    env_file:
      - .env


volumes:
  es_data: