version: "3"

services:
  postgres:
    image: postgres:12.4
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./etl/sqlite_to_postgres/psql_schema.sql:/docker-entrypoint-initdb.d/psql_schema.sql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    env_file:
      - .env

  redis:
    image: redis
    command:
      - redis-server
    env_file:
      - .env

  etl:
    build: ./etl
    env_file:
      - .env
    depends_on:
      - postgres
      - elasticsearch
    volumes:
      - etl_data:/etl

  backend_api:
    build: src/
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - elasticsearch
    ports:
      - '8000:8000'
    volumes:
      - ./src/:/api/

volumes:
  es_data:
  postgres_data:
  etl_data: