version: "3"

services:
  db:
    image: postgres:12.4
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./etl/sqlite_to_postgres/psql_schema.sql:/docker-entrypoint-initdb.d/psql_schema.sql
    expose:
      - 5432

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    expose:
      - 9200
    env_file:
      - .env

  redis:
    image: redis
    expose:
      - 6379
    command:
      - redis-server
    env_file:
      - .env

  etl:
    build: ./etl
    env_file:
      - .env
    depends_on:
      - db
      - es


volumes:
  es_data:
  postgres_data: