version: "3.8"

services:
  postgres_test:
    image: postgres:12.4
    restart: always
    env_file:
      - .env

  redis_test:
    image: redis
    command:
      - redis-server

  tests:
    build:
      context: .
      target: tests
    env_file:
      - .env
    environment:
      - DB_HOST=postgres_test
      - DB_PORT=5432
      - REDIS_HOST=redis_test
      - RPS_COUNT=1000
    depends_on:
      - postgres_test
      - redis_test
