version: "3.8"

services:
  postgres:
    image: postgres:12.4
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis
    command:
      - redis-server
    env_file:
      - .env

  auth_service:
    build:
      context: .
      target: prod
    image: auth_service_image
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    ports:
      - '8001:5000'

volumes:
  postgres_data: