version: "3"

services:
  postgres:
    image: postgres:12.4
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5439:5432"

  redis:
    image: redis
    command:
      - redis-server
    env_file:
      - .env
    ports:
      - "6379:6379"

volumes:
  postgres_data: