"""empty message

Revision ID: 244bd234e505
Revises: 71b53fb3c69a
Create Date: 2022-02-25 23:53:18.894311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244bd234e505'
down_revision = '71b53fb3c69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    # ### end Alembic commands ###
