"""empty message

Revision ID: 83056982da0c
Revises: 244bd234e505
Create Date: 2022-02-25 23:54:21.437072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83056982da0c'
down_revision = '244bd234e505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'auth_history', ['id', 'user_device_type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_history', type_='unique')
    # ### end Alembic commands ###
