FROM python:3.9
RUN  apt-get update && apt-get install -y netcat && pip install --upgrade pip

WORKDIR /api

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .
CMD ["gunicorn", "main:app", "--workers", "4",  "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]